### ISSUE TITLE
When adding new connection, it cannot load Safe modules

### ISSUE THREAD

**Issue by jfschwarz** [gnosis/zodiac-pilot#17]
I believe we had this issue in the past and brute-force-fixed it with `window.reload` back then.

**Comment by auryn-macmillan** [comment]
I've just run into this same issue.

![image](https://user-images.githubusercontent.com/8453294/183817577-79b1e08e-032d-4924-895c-fa802cd57c34.png)

**Comment by auryn-macmillan** [comment]
Ah ha!
Turns out you get this issue if the pilot is not enabled as a module on the modifier.

**Comment by auryn-macmillan** [comment]
Although I'm now running into a separate issue.
![image](https://user-images.githubusercontent.com/8453294/183822236-082e0ce1-9431-459f-a191-4a929580710a.png)
